Repository hugsy/gef, pull requests merged in 2021-11, with the labels that each got.

#745 add number arg for 'heap chunk' command
  docs/commands/heap.md
  gef.py
  tests/runtests.py
Labels: enhancement

#754 Remove the `assert` on `get_register`
  gef.py
Labels: bug, compatibility, ready-for-review

#758 add support for hex strings to print-format
  docs/commands.md
  docs/commands/print-format.md
  gef.py
  tests/runtests.py
Labels: enhancement, ready-for-review
