Repository hugsy/gef, pull requests merged in 2021-09, with the labels that each got.

#703 Update docs for several commands
  docs/commands/elf-info.md
  docs/commands/heap-analysis-helper.md
  docs/commands/help.md
  docs/commands/hexdump.md
  docs/commands/process-search.md
  docs/commands/process-status.md
  docs/commands/registers.md
  docs/commands/scan.md
  docs/commands/set-permission.md
  docs/commands/tmux-setup.md
  docs/commands/version.md
  gef.py
Labels: enhancement, documentation

#701 Update and fix heap command
  docs/commands/heap.md
  gef.py
  tests/binaries/heap-fastbins.c
  tests/runtests.py
Labels: bug, enhancement, new feature, documentation, compatibility

#713 Fix unicorn-emulate cmd
  docs/commands/unicorn-emulate.md
  gef.py
  tests/runtests.py
Labels: bug, enhancement, documentation

#714 Use `pytest` on top of `unittest` to allow multi-proc execution
  .github/workflows/run-tests.yml
  Makefile
  README.md
  requirements.txt
  tests/binaries/unicorn.c
  tests/runtests.py
Labels: enhancement, automation

#715 Fix context failed to execute because breakpoint.location is None
  gef.py
Labels: bug

#717 Backport Elf / ElfInfoCommand updates
  docs/commands/elf-info.md
  gef.py
Labels: enhancement, new feature, documentation

#716 Fix heap chunks cmd for multiple heaps per arena
  docs/commands/heap.md
  gef.py
  tests/runtests.py
Labels: bug, enhancement

#718 Configuration for the stale bot
  .github/stale.yml
Labels: automation

#711 Add test for printing chunks with multiple heaps
  tests/binaries/Makefile
  tests/binaries/heap-multiple-heaps.c
  tests/runtests.py
Labels: automation

#722 Add feature to print heap chunks of all arenas
  docs/commands/heap.md
  gef.py
  tests/runtests.py
Labels: enhancement

#723 refactor: use parse_address whenever appropriate
  gef.py
Labels: enhancement

#720 Adding unit tests for non-x86 architectures
  .github/workflows/run-tests.yml
  Makefile
  gef.py
  tests/binaries/Makefile
  tests/binaries/bss.c
  tests/binaries/heap-fastbins.c
  tests/binaries/heap-non-main.c
  tests/binaries/heap-tcache.c
  tests/binaries/heap.c
  tests/binaries/memwatch.c
  tests/binaries/nested.c
  tests/binaries/nested2.c
  tests/binaries/set-permission.c
  tests/binaries/utils.h
  tests/helpers.py
  tests/runtests.py
Labels: enhancement, automation

#725 CI: Lint: Add more linters to test files
  Makefile
  tests/helpers.py
  tests/runtests.py
Labels: ready-for-review

#727 Support for custom contexts in ContextCommand
  docs/api.md
  docs/commands/context.md
  gef.py
Labels: enhancement, documentation, api-change

#731 [CI] Use Actions to check URL links in the documentation
  .ci/mlc_config.json
  .github/workflows/docs-link-check.yml
  .gitignore
  docs/commands.md
  docs/commands/ida-interact.md
  docs/faq.md
Labels: documentation, automation, ready-for-review

#732 Allow empty context titles
  docs/api.md
  gef.py
Labels: enhancement, documentation

#733 Review
  docs/commands/aliases.md
  docs/commands/functions.md
  docs/commands/ksymaddr.md
  docs/commands/pattern.md
  docs/commands/reset-cache.md
  docs/commands/stub.md
  docs/commands/vmmap.md
  docs/index.md
  docs/screenshots.md
  gef.py
  tests/helpers.py
  tests/runtests.py
Labels: documentation, ready-for-review
