Repository hugsy/gef, pull requests merged in 2022-01, with the labels that each got.

#768 refactor: use f-strings across codebase
  gef.py
Labels: code-quality

#780 tests: add tests for heap bins small, large and unsorted cmd
  tests/binaries/Makefile
  tests/binaries/heap-bins.c
  tests/runtests.py
Labels: documentation, automation

#779 GEF code quality improvement, with support with GDB 8+ and Python3.6+
  .github/workflows/run-tests.yml
  README.md
  docs/api.md
  docs/api/gef.md
  docs/compat.md
  docs/config.md
  docs/faq.md
  docs/index.md
  gef.py
  mkdocs.yml
  scripts/generate-api-docs.sh
  tests/helpers.py
  tests/runtests.py
Labels: enhancement, documentation, code-quality

#792 Fixed bugs in `GefSetting` that prevented saved values to be loaded
  gef.py
Labels: bug, regression

#796 updated add_context_pane settings use
  gef.py
Labels: bug, confirmed

#795 `@deprecated` warning display can be toggled off
  gef.py
Labels: enhancement

#797 refactor: add missing py3.6 type hints
  gef.py
Labels: code-quality

#794 Complete rewrite of `pcustom` command
  gef.py
  tests/binaries/pcustom.c
  tests/runtests.py
Labels: enhancement, new feature, code-quality

#798 ELF class upgrades
  gef.py
  tests/runtests.py
Labels: api-change, code-quality
