Repository hugsy/gef, pull requests merged in 2022-07, with the labels that each got.

#861 Move `syscall-args` and `is-syscall` to gef-extras
  docs/commands/is-syscall.md
  docs/commands/syscall-args.md
  docs/deprecated.md
  gef.py
  mkdocs.yml
  tests/binaries/mmap-known-address.c
  tests/binaries/set-permission.c
  tests/binaries/syscall-args.c
  tests/commands/nop.py
  tests/commands/syscall_args.py
Labels: code-quality

#868 Fixed TinyUrl links to point to `main`, not `master`
  README.md
  docs/install.md
Labels: bug

#866 Remove `glibc-function-args`
  gef.py
Labels: code-quality

#869 `Glibc*` class now rely on `ctypes.Structure`
  docs/api/gef.md
  gef.py
  tests/commands/heap.py
Labels: enhancement

#876 Fix ptrsize for ARM to not return 2 ever
  gef.py
Labels: bug
