Repository hugsy/gef, pull requests merged in 2022-06, with the labels that each got.

#842 Remove `ida-interact`
  docs/api/gef.md
  docs/commands/ida-interact.md
  docs/commands/pcustom.md
  docs/deprecated.md
  gef.py
  mkdocs.yml
  scripts/ida_gef.py
Labels: documentation, code-quality

#839 Type hinting fixes - part 2
  Makefile
  gef.py
  tests/binaries/Makefile
  tests/commands/gef.py
Labels: bug, documentation, automation, api-change, code-quality

#843 new feature: print-format and patch byte commands can work together
  docs/commands/patch.md
  docs/commands/print-format.md
  gef.py
  tests/commands/patch.py
  tests/commands/print_format.py
Labels: enhancement, documentation

#848 fix typo in patch byte help
  gef.py
Labels: documentation

#830 Better `gef-remote` : rewrite and add `remote` full support
  gef.py
  tests/api/misc.py
  tests/commands/gef_remote.py
  tests/utils.py
Labels: enhancement, api-change, code-quality

#846 Better `gef-remote` - part 2: Remote Qemu
  docs/commands/gef-remote.md
  gef.py
  tests/commands/gef_remote.py
  tests/utils.py
Labels: enhancement, documentation, code-quality

#852 Minor update to unittest of `print-format` after #843
  tests/commands/print_format.py
Labels: enhancement, automation

#851 Fix 850
  gef.py
Labels: bug

#849 Allow new file format
  gef.py
Labels: enhancement, new feature, documentation, api-change, code-quality

#858 [pattern-search] Make sure pattern is correctly built
  gef.py
  tests/commands/pattern.py
Labels: bug
