Repository hugsy/gef, pull requests merged in 2023-07, with the labels that each got.

#969 Restore `autosave_breakpoints_file` behavior
  LICENSE
  gef.py
Labels: bug, regression

#971 Fix hardcoded NOP instructions for ARM/AARCH64
  gef.py
  tests/commands/nop.py
Labels: bug, arch: arm/arm64

#976 reformat README
  README.md
Labels: documentation
