Repository hugsy/gef, pull requests merged in 2023-08, with the labels that each got.

#975 Minor additions to the documentation
  README.md
  docs/index.md
  docs/install.md
  mkdocs.yml
Labels: documentation

#977 [Docs] Added linting for markdown files
  .editorconfig
  docs/.markdownlint.yaml
  docs/api.md
  docs/commands/aslr.md
  docs/commands/canary.md
  docs/commands/checksec.md
  docs/commands/config.md
  docs/commands/context.md
  docs/commands/dereference.md
  docs/commands/edit-flags.md
  docs/commands/format-string-helper.md
  docs/commands/functions.md
  docs/commands/gef-remote.md
  docs/commands/gef.md
  docs/commands/got.md
  docs/commands/heap-analysis-helper.md
  docs/commands/heap.md
  docs/commands/highlight.md
  docs/commands/hijack-fd.md
  docs/commands/memory.md
  docs/commands/name-break.md
  docs/commands/nop.md
  docs/commands/pcustom.md
  docs/commands/print-format.md
  docs/commands/process-search.md
  docs/commands/reset-cache.md
  docs/commands/search-pattern.md
  docs/commands/shellcode.md
  docs/commands/skipi.md
  docs/commands/trace-run.md
  docs/commands/xor-memory.md
  docs/compat.md
  docs/faq.md
  docs/functions/base.md
  docs/functions/bss.md
  docs/functions/got.md
  docs/functions/heap.md
  docs/functions/stack.md
  docs/index.md
  docs/install.md
  docs/obsolete/docs/index.md
  docs/testing.md
Labels: documentation

#980 under license mit -> under mit license
  .github/CONTRIBUTING.md
Labels: documentation

#982 Switch dev refs to main
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/generate-docs.yml
  .github/workflows/notify.yml
  .github/workflows/run-tests.yml
  README.md
  docs/api.md
  docs/commands/gef.md
  docs/commands/pcustom.md
  docs/deprecated.md
  docs/install.md
  gef.py
  scripts/gef-extras.sh
  scripts/gef.sh
  scripts/generate-api-docs.sh
  tests/api/misc.py
Labels: code-quality

#985 add debugging instructions
  docs/debugging.md
  mkdocs.yml
Labels: documentation

#990 [CI] Use `pull_request_target` for coverage trigger
  .github/workflows/coverage.yml
Labels: automation/ci
