Repository hugsy/gef, pull requests merged in 2024-06, with the labels that each got.

#1114 [cmd] Add a `arch` command for managing `gef.arch`
  docs/commands/arch.md
  gef.py
  tests/commands/arch.py
Labels: new feature

#1116 [Release 2024.06] Fixes
  tests/api/gef_memory.py
  tests/api/gef_session.py
  tests/commands/canary.py
  tests/commands/gef_remote.py
  tests/commands/scan.py
  tests/commands/vmmap.py
Labels: automation/ci

#1118 Reload settings if gef-extras scripts were loaded
  gef.py
Labels: bug
