Repository hugsy/gef, pull requests merged in 2024-04, with the labels that each got.

#1076 `flag_register_to_human` is not implemented on RISC-V architecture
  gef.py
Labels: bug, api-change, arch: riscv/riscv64

#1084 Remove pyenv related code (closes #1078)
  docs/deprecated.md
  gef.py
Labels: code-quality

#1087 add skipi to docs
  mkdocs.yml
Labels: documentation, fixed

#1086 add stepover command
  docs/commands/stepover.md
  gef.py
  mkdocs.yml
  tests/commands/stepover.py
Labels: feature-request

#1090 Add `on_changed` setting hook
  gef.py
Labels: enhancement, api-change

#1093 add layout mapping API for external plugins
  docs/api.md
  gef.py
  scripts/gef-extras.sh
Labels: documentation, ui
