Repository hugsy/gef, pull requests merged in 2024-07, with the labels that each got.

#1126 [License] 2023 -> 2024
  LICENSE
  gef.py
Labels: documentation

#1115 [CI] Add new runner: Ubuntu 2404
  .github/workflows/run-tests.yml
  .github/workflows/tests.yml
Labels: automation/ci

#1109 Fix remote use of gef.memory.maps
  gef.py
  tests/api/gef_memory.py
Labels: bug, enhancement
